# Generated by Django 5.0.6 on 2026-03-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('fecha_matricula', models.DateField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('retirado', 'Retirado'), ('graduado', 'Graduado'), ('trasladado', 'Trasladado')], default='activa', max_length=20)),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
                'ordering': ['-year', 'id_estudiante'],
            },
        ),
    ]
