# Generated by Django 5.0.6 on 2026-03-26 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('enrollment', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='id_estudiante',
            field=models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='students.estudiante'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='id_grado',
            field=models.ForeignKey(db_column='id_grado', on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='academic.grado'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('id_estudiante', 'id_grado', 'year'), name='matricula_unique'),
        ),
    ]
