# Generated by Django 5.0.6 on 2026-03-26 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grado',
            name='id_docente',
            field=models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grados', to='academic.docente'),
        ),
        migrations.AddConstraint(
            model_name='periodo',
            constraint=models.UniqueConstraint(fields=('numero_periodo', 'year'), name='periodo_unique'),
        ),
    ]
