# Generated by Django 5.0.6 on 2026-03-26 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id_nota', models.BigAutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('observacion', models.TextField(blank=True, null=True)),
                ('id_materia', models.ForeignKey(db_column='id_materia', on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='academic.materia')),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='enrollment.matricula')),
                ('id_periodo', models.ForeignKey(db_column='id_periodo', on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='academic.periodo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['id_matricula', 'id_periodo', 'id_materia'],
            },
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('id_matricula', 'id_materia', 'id_periodo'), name='nota_unique'),
        ),
    ]
