# Generated by Django 5.0.6 on 2026-03-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'acudiente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('numero_identidad', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('rh', models.CharField(blank=True, max_length=5, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RelacionEA',
            fields=[
                ('id_relacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('acudiente_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Relación Estudiante-Acudiente',
                'verbose_name_plural': 'Relaciones Estudiante-Acudiente',
                'db_table': 'relacion_ea',
            },
        ),
    ]
