# Generated by Django 5.0.6 on 2026-03-26 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acudiente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acudiente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relacionea',
            name='id_acudiente',
            field=models.ForeignKey(db_column='id_acudiente', on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='students.acudiente'),
        ),
        migrations.AddField(
            model_name='relacionea',
            name='id_estudiante',
            field=models.ForeignKey(db_column='id_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='acudientes', to='students.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='relacionea',
            unique_together={('id_estudiante', 'id_acudiente')},
        ),
    ]
