# Generated by Django 5.0.6 on 2026-03-26 00:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoPago',
            fields=[
                ('id_concepto_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Concepto de Pago',
                'verbose_name_plural': 'Conceptos de Pago',
                'db_table': 'concepto_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodo_pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCobro',
            fields=[
                ('id_cuenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('year', models.IntegerField()),
                ('valor_deuda', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=20)),
                ('id_concepto_pago', models.ForeignKey(db_column='id_concepto_pago', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='payments.conceptopago')),
                ('id_matricula', models.ForeignKey(db_column='id_matricula', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cobro', to='enrollment.matricula')),
            ],
            options={
                'verbose_name': 'Cuenta de Cobro',
                'verbose_name_plural': 'Cuentas de Cobro',
                'db_table': 'cuenta_cobro',
                'ordering': ['-year', '-mes'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cuenta_cobro', models.ForeignKey(db_column='id_cuenta_cobro', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='payments.cuentacobro')),
                ('id_metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='payments.metodopago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
